### ISSUE TITLE
Issue Network Unwrap

### ISSUE THREAD

**Issue by albertpv** [RestComm/jdiameter#120]
When starting JDiamerter have issue in following piece of code:

3693 [main] INFO  org.jdiameter.client.impl.StackImpl  - (-)(-)(-)(-)(-) Started  Mobicents DIAMETER Stack v1.7.0.109 (-)(-)(-)(-)(-)
3707 [main] ERROR root  - cannot add network listener :-( java.lang.NullPointerException
java.lang.NullPointerException
        at org.jdiameter.client.impl.StackImpl.unwrap(StackImpl.java:441)
        at net.genaker.rxconnector.RxClient.<init>(RxClient.java:104)
        at net.genaker.rxconnector.RxConnector.main(RxConnector.java:53)
3861 [main] INFO  root  - Client Stack started!
3864 [main] INFO  root  - local peer [CPeer{Uri=aaa://10.81.194.131:3868; State=DOWN; Con=org.jdiameter.client.impl.transport.tcp.TCPClientConnection@2ff55105}]
4266 [main] INFO  org.mortbay.log  - Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog

	config = new XMLConfiguration(is);
logger.info("Client Stack config loaded!");
        serverURI = "aaa://" + serverHost + ":" + serverPort;
        logger.info("RXConnector: setup to send Rx Request to ip :"+ serverHost+ " uri:"+serverURI);
		clientFactory = clientStack.init(config);
        Network network = null;
        try{
			 **network = clientStack.unwrap(Network.class);**
             network.addNetworkReqListener(this, this.authAppId); //passing our example app id.
        }catch(Exception e){
			logger.error("cannot add network listener :-( "+e);
			e.printStackTrace();
		}
		if(is!=null){
			is.close();
		}

Then as network request listener is not succesfully added do not receive callbacks on diameter answers send to my client. However my client can succesfully send requests without issues.

What could be cause of this issue in unwrap?

**Comment by gsaslis** [comment]
@albertpv just a quick check: Where you able to figure this out / work around it?

Or is this still an open issue?

**Comment by webjaym** [comment]
Hi @albertpv / @gsaslis   : Did you get any solution for above issue? I am also looking for solution to same.
