### ISSUE TITLE
Error file config xml when run Example

### ISSUE THREAD

**Issue by nguyenbatam** [RestComm/jdiameter#64]
When I run example server and example client  i has error .
0    [main] DEBUG com.xkeam.example.diameter.ExampleServer  - log4j configured
4    [main] INFO  com.xkeam.example.diameter.ExampleServer  - Initializing Stack...
SLF4J: The requested version 1.5.8 by your slf4j binding is not compatible with [1.6, 1.7]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
77   [main] INFO  com.xkeam.example.diameter.ExampleServer  - AVP Dictionary successfully parsed.
296  [main] INFO  org.jdiameter.client.impl.StackImpl  - (-)(-)(-)(-)(-) Starting Mobicents DIAMETER Stack v1.7.0.106 (-)(-)(-)(-)(-)
Exception in thread "main" java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.format(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
	at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:223)
	at org.jdiameter.common.impl.controller.AbstractPeer.createPeerStatistics(AbstractPeer.java:88)
	at org.jdiameter.client.impl.MetaDataImpl$ClientLocalPeer.<init>(MetaDataImpl.java:242)
	at org.jdiameter.server.impl.MetaDataImpl$ServerLocalPeer.<init>(MetaDataImpl.java:154)
	at org.jdiameter.server.impl.MetaDataImpl.newLocalPeer(MetaDataImpl.java:104)
	at org.jdiameter.client.impl.MetaDataImpl.<init>(MetaDataImpl.java:122)
	at org.jdiameter.server.impl.MetaDataImpl.<init>(MetaDataImpl.java:94)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:147)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:332)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:272)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:354)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:692)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:105)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:76)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:299)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:325)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:272)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:354)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:692)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:671)
	at org.jdiameter.client.impl.helpers.AssemblerImpl.getComponentInstance(AssemblerImpl.java:152)
	at org.jdiameter.client.impl.StackImpl.init(StackImpl.java:166)
	at com.xkeam.example.diameter.ExampleServer.initStack(ExampleServer.java:115)
	at com.xkeam.example.diameter.ExampleServer.main(ExampleServer.java:244)

All the code is newest , i clone it today , and not change any thing , Pls help me

**Comment by xphudin** [comment]
Please tell us your steps ?
Did you follow http://documentation.telestax.com/core/tutorials/jdiameter-quick-telscale-diameter-performance-testing-using-seagull.html ?
Thanks

**Comment by xphudin** [comment]
hi.
SLF4J: The requested version 1.5.8 by your slf4j binding is not compatible with [1.6, 1.7]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
You should try update your slf4j version to 1.6 or 1.7 in pom file.

**Comment by nguyenbatam** [comment]
thank you very muck , I fixed its
